<?
  if($loggedin = $this->auth()->isLoggedIn()) {
    $user_id = $loggedin->id;
    $loggedin = true;
  } else {
    $user_id = false;
  }
?>
<div class="row" vocab="http://schema.org/" resource="#record" typeof="<?=$this->driver->getSchemaOrgFormats()?> Product">
  <?
  $QRCode = $this->record($this->driver)->getQRCode("core");
  $coverDetails = $this->record($this->driver)->getCoverDetails('result-list', 'medium', $this->recordLink()->getUrl($this->driver));
  $preview = $this->record($this->driver)->getPreviews();
  ?>

    <!--
    <? $potentialZenonRecords = $this->recordLink()->getMovedZenonRecordId($this->currentPath()); ?>
    <? if($potentialZenonRecords): ?>
        <div class="alert alert-success moved-record" role="alert">
            <p>
                <?=$this->transEsc('Zenon record moved'); ?>
                <a class="alert-link" href="/Record/<?= $potentialZenonRecords ?>">
                    <i class="fa fa-angle-double-right" aria-hidden="true"></i> <?= $potentialZenonRecords ?>
                </a>
            </p>
        </div>
    <? endif; ?>
    -->
  <? if ($QRCode || $coverDetails['cover'] || strlen($preview) > 0): ?>
  <div class="col-sm-3">
    <div class="text-center">
      <? /* Display thumbnail if appropriate: */ ?>
      <? if($coverDetails['cover']): ?>
        <?= $coverDetails['html']; ?>
      <? endif; ?>

      <? /* Display qrcode if appropriate: */ ?>
      <? if($QRCode): ?>
        <span class="hidden-xs">
          <br/><img alt="<?=$this->transEsc('QR Code')?>" class="qrcode" src="<?=$this->escapeHtmlAttr($QRCode);?>"/>
        </span>
      <? endif; ?>
    </div>

    <? // if you have a preview tab but want to move or remove the preview link
       // from this area of the record view, this can be split into
       // getPreviewData() (should stay here) and
       // getPreviewLink() (can go in your desired tab) ?>
    <? if ($preview): ?><?=$preview?><? endif; ?>
  </div>

  <div class="col-sm-9">
  <? else: ?>
  <div class="col-sm-12">
  <? endif; ?>

    <h3 property="name">
        <?=$this->escapeHtml($this->driver->getShortTitle()); ?>
        <? if(!empty($this->driver->getSubtitle())): ?>
            <?= $this->escapeHtml(' ' .  $this->escapeHtml($this->driver->getSubtitle())); ?>
        <? endif ?>
        <? if(!empty($this->driver->getTitleSection())): ?>
            <?= $this->escapeHtml(' ' .  $this->escapeHtml($this->driver->getTitleSection())); ?>
        <? endif ?>
    </h3>

    <? $summary = $this->driver->getSummary(); $summary = isset($summary[0]) ? $this->escapeHtml($summary[0]) : false; ?>
    <? if ($summary): ?>
      <p><?=$this->truncate($summary, 300)?></p>

      <? if(strlen($summary) > 300): ?>
        <p><a href='<?=$this->recordLink()->getTabUrl($this->driver, 'Description')?>#tabnav'><?=$this->transEsc('Full description')?></a></p>
      <? endif; ?>
    <? endif; ?>

    <? if ($this->userlist()->getMode() !== 'disabled'): ?>
      <? /* Display the lists that this record is saved to */ ?>
      <div class="savedLists hidden alert alert-info" id="savedLists">
        <strong><?=$this->transEsc("Saved in")?>:</strong>
      </div>
    <? endif; ?>

    <table class="table table-striped" summary="<?=$this->transEsc('Bibliographic Details')?>">

      <? $nextTitles = $this->driver->getNewerTitles(); $prevTitles = $this->driver->getPreviousTitles(); ?>
      <? if (!empty($nextTitles)): ?>
      <tr>
        <th><?=$this->transEsc('New Title')?>: </th>
        <td>
          <? foreach($nextTitles as $field): ?>
            <a href="<?=$this->record($this->driver)->getLink('title', $field)?>"><?=$this->escapeHtml($field)?></a><br/>
          <? endforeach; ?>
        </td>
      </tr>
      <? endif; ?>

      <? if (!empty($prevTitles)): ?>
      <tr>
        <th><?=$this->transEsc('Previous Title')?>: </th>
        <td>
          <? foreach($prevTitles as $field): ?>
            <a href="<?=$this->record($this->driver)->getLink('title', $field)?>"><?=$this->escapeHtml($field)?></a><br/>
          <? endforeach; ?>
        </td>
      </tr>
      <? endif; ?>

      <? $varyingTitles = $this->driver->getVaryingFormOfTitles(); $additionalTitles = $this->driver->getAdditionalTitles(); ?>
      <? if (!empty($varyingTitles)): ?>
      <tr>
        <th><?=$this->transEsc('Varying Form of Title')?>: </th>
        <td>
          <? foreach($varyingTitles as $field): ?>
            <a href="<?=$this->record($this->driver)->getLink('title', $field)?>"><?=$this->escapeHtml($field)?></a><br/>
          <? endforeach; ?>
        </td>
      </tr>
      <? endif; ?>

      <? if (!empty($additionalTitles)): ?>
      <tr>
        <th><?=$this->transEsc('Additional Title')?>: </th>
        <td>
          <? foreach($additionalTitles as $field): ?>
            <a href="<?=$this->record($this->driver)->getLink('title', $field)?>"><?=$this->escapeHtml($field)?></a><br/>
          <? endforeach; ?>
        </td>
      </tr>
      <? endif; ?>

      <? $authors = $this->driver->getDeduplicatedAuthors(); ?>
      <? if (isset($authors['primary']) && !empty($authors['primary'])): ?>
      <tr>
        <th><?=$this->transEsc('Main Author')?>: </th>
        <? foreach($authors['primary'] as $author=>$value): ?>
          <td property="author">
              <a href="<?=$this->record($this->driver)->getLink('author',$author)?>">
                  <?=$this->escapeHtml($author)?>
                    <? if (!empty($value['role'])): ?>
                        <? foreach ($value['role'] as $role): ?>
                            , [<?=$this->transEsc('CreatorRoles::' . $role)?>]
                        <? endforeach ?>
                    <? endif ?>
              </a>
          </td>
        <? endforeach; ?>
      </tr>
      <? endif; ?>

      <? if (isset($authors['corporate']) && !empty($authors['corporate'])): ?>
      <tr>
        <th><?=$this->transEsc('Corporate Author')?>: </th>
        <td property="creator">
        <? foreach($authors['corporate'] as $author=>$key): ?>
            <a href="<?=$this->record($this->driver)->getLink('author', $author)?>">
                <?=$this->escapeHtml($author)?>
            </a>
            <br/>
        <? endforeach; ?>
        </td>
      </tr>
      <? endif; ?>

      <? if (isset($authors['secondary']) && !empty($authors['secondary'])): ?>
      <tr>
        <th><?=$this->transEsc('Other Authors')?>: </th>
        <td>
          <? $i = 0; foreach ($authors['secondary'] as $author=>$value): ?>
            <?=($i++ == 0)?'':', '?>
            <span property="contributor">
              <a href="<?=$this->record($this->driver)->getLink('author', $author)?>">
                  <?=$this->escapeHtml($author)?>
                  <? if (!empty($value['role'])): ?>
                      <? foreach ($value['role'] as $role): ?>
                          , [<?=$this->transEsc('CreatorRoles::' . $role)?>]
                      <? endforeach ?>
                  <? endif ?>
              </a>
            </span>
          <? endforeach; ?>
        </td>
      </tr>
      <? endif; ?>

      <?/* commented out (with if false) since formats are not properly set in zenon data yet */?>
      <? $formats = $this->driver->getFormats(); if (false && !empty($formats)): ?>
        <tr>
          <th><?=$this->transEsc('Format')?>: </th>
          <td><?=$this->record($this->driver)->getFormatList()?></td>
        </tr>
      <? endif; ?>

      <?/* commented out (with if false) since languages are not properly set in zenon data yet */?>
      <? $langs = $this->driver->getLanguages(); if (false && !empty($langs)): ?>
        <tr>
          <th><?=$this->transEsc('Language')?>: </th>
          <td><? foreach ($langs as $lang): ?><?= $this->escapeHtml($lang)?><br/><? endforeach; ?></td>
        </tr>
      <? endif; ?>

      <? $publications = $this->driver->getPublicationDetails(); if (!empty($publications)): ?>
      <tr>
        <th><?=$this->transEsc('Published')?>: </th>
        <td>
          <? foreach ($publications as $field): ?>
            <span property="publisher" typeof="Organization">
            <? $pubPlace = $field->getPlace(); if (!empty($pubPlace)): ?>
              <span property="location"><?=$this->escapeHtml($pubPlace)?></span>
            <? endif; ?>
            <? $pubName = $field->getName(); if (!empty($pubName)): ?>
              <span property="name"><?=$this->escapeHtml($pubName)?></span>
            <? endif; ?>
            </span>
            <? $pubDate = $field->getDate(); if (!empty($pubDate)): ?>
              <span property="publicationDate"><?=$this->escapeHtml($pubDate)?></span>
            <? endif; ?>
            <br/>
          <? endforeach; ?>
        </td>
      </tr>
      <? endif; ?>

      <? $edition = $this->driver->getEdition(); if (!empty($edition)): ?>
      <tr>
        <th><?=$this->transEsc('Edition')?>: </th>
        <td property="bookEdition"><?=$this->escapeHtml($edition)?></td>
      </tr>
      <? endif; ?>


<? // Physische Beschreibung hinzugefügt, 07.06.2016 ?>
<? // übernommen aus themes/archaeostrap/templates/RecordTab/description.phtml ?>
  <? $physical = $this->driver->getPhysicalDescriptions(); if (!empty($physical)): ?>
    <tr>
      <th><?=$this->transEsc('Physical Description')?>: </th>
      <td>
        <? foreach ($physical as $field): ?>
          <?=$this->escapeHtml($field)?><br/>
        <? endforeach; ?>
      </td>
    </tr>
<? endif; ?>

      <?/* Display series section if at least one series exists. */?>
      <? $series = $this->driver->getSeries(); if (!empty($series)): ?>
      <tr>
        <th><?=$this->transEsc('Series')?>: </th>
        <td>
          <? foreach ($series as $field): ?>
            <?/* Depending on the record driver, $field may either be an array with
               "name" and "number" keys or a flat string containing only the series
               name.  We should account for both cases to maximize compatibility. */?>
            <? if (is_array($field)): ?>
              <? if (!empty($field['name'])): ?>
                <a href="<?=$this->record($this->driver)->getLink('series', $field['name'])?>"><?=$this->escapeHtml($field['name'])?></a>
                <? if (!empty($field['number'])): ?>
                  <?=$this->escapeHtml($field['number'])?>
                <? endif; ?>
                <br/>
              <? endif; ?>
            <? else: ?>
              <a href="<?=$this->record($this->driver)->getLink('series', $field)?>"><?=$this->escapeHtml($field)?></a><br/>
            <? endif; ?>
          <? endforeach; ?>
        </td>
      </tr>
      <? endif; ?>

      <? $subjects = $this->driver->getAllSubjectHeadings(); if (!empty($subjects)): ?>
      <tr>
        <th><?=$this->transEsc('Subjects')?>: </th>
        <td>
          <? foreach ($subjects as $field): ?>
          <div class="subjectLine" property="keywords">
            <? $subject = ''; ?>
            <? if(count($field) == 1) $field = explode('--', $field[0]); ?>
            <? $i = 0; foreach ($field as $subfield): ?>
              <?=($i++ == 0) ? '' : ' &gt; '?>
              <? $subject = trim($subject . ' ' . $subfield); ?>
              <a class="label label-default" title="<?=$this->escapeHtmlAttr($subject)?>" href="<?=$this->record($this->driver)->getLink('subject', $subject)?>" rel="nofollow"><?=trim($this->escapeHtml($subfield))?></a>
            <? endforeach; ?>
          </div>
          <? endforeach; ?>
        </td>
      </tr>
      <? endif; ?>

      <?/* display connected zenon thesaurus concepts */?>
      <? $thsEntries = $this->driver->getThsEntries(); ?>
      <? if(!empty($thsEntries)): ?>
        <tr>
          <th><?=$this->transEsc('Thesaurus')?>: </th>
          <td>
            <? foreach ($thsEntries as $thsEntry): ?>
            <div>
              <a class="label label-default" title="<?=$this->escapeHtml($thsEntry['label'])?>" href="<?=$this->record($this->driver)->getLink('thesaurus', $thsEntry['notation'])?>">
                <?=$this->escapeHtml($thsEntry['label'])?> <small style="font-weight:normal"><?=$this->escapeHtml($thsEntry['notation'])?></small>
              </a>
            </div>
            <? endforeach; ?>
          </td>
        </tr>
      <? endif; ?>

      <?/* display links to gazetteer */?>
      <? $gazLinks = $this->driver->getGazetteerLinks(); ?>
      <? if(!empty($gazLinks)): ?>
        <tr>
          <th>iDAI.gazetteer: </th>
          <td>
            <? foreach ($gazLinks as $gazLink): ?>
              <a title="<?=$this->escapeHtml($gazLink['label'])?>" href="<?=$gazLink['uri']?>" target="_blank"><i class="fa fa-map-marker"></i> <?=$this->escapeHtml($gazLink['label'])?> <small><i class="fa fa-external-link"></i></small></a><br />
            <? endforeach; ?>
          </td>
        </tr>
      <? endif; ?>

      <? $publicationsLink = $this->driver->getPublicationsLink(); ?>
      <? if($publicationsLink): ?>
          <tr>
              <th>iDAI.publications</th>
              <td>
                  <a href="<?=$publicationsLink?>" target="_blank"><?=$publicationsLink?> <small><i class="fa fa-external-link"></i></small></a>
              </td>
          </tr>
      <? endif; ?>

      <tr id="arachne-data" control-number="<?= $this->driver->getControlNumber(); ?>"></tr>

      <? $locations = $this->driver->getLocation(); ?>
      <? if($locations): ?>
        <tr>
          <th><?=$this->transEsc('Location')?>: </th>
          <td>
            <? foreach ($locations as $location): ?>
              <?=$this->escapeHtml($location)?><br />
            <? endforeach; ?>
          </td>
        </tr>
      <? endif; ?>

      <? $units = $this->driver->getBasicBibliographicUnit(); ?>
      <? if($units): ?>
        <tr>
          <th><?=$this->transEsc('Summary holding')?>: </th>
          <td>
            <? foreach ($units as $unit): ?>
              <?=$this->escapeHtml($unit)?><br />
            <? endforeach; ?>
          </td>
        </tr>
      <? endif; ?>

      <? $hostItems = $this->driver->getHostItemInformation(); ?>
      <? if(!empty($hostItems)): ?>
        <tr>
          <th><?=$this->transEsc('Included in')?>: </th>
          <td>
            <? foreach ($hostItems as $hostItem): ?>
                <? if($hostItem['id']): ?>
                    <a title="<?=$this->escapeHtml($hostItem['label'])?>"
                       href="<?=$this->url('record', array('id' => $hostItem['id']))?>">
                        <i class="fa fa-book"></i> <?=$this->escapeHtml($hostItem['label'])?>
                    </a>
                <? else: ?>
                    <?=$this->escapeHtml($hostItem['label'])?>
                <? endif; ?>
            <? endforeach; ?>
          </td>
        </tr>
      <? endif; ?>

      <? $chreLink = $this->driver->getCHRELink(); ?>
      <? if(!empty($chreLink)): ?>
        <tr>
          <th>CHRE:</th>
          <td>
            <a href="<?=$chreLink?>" target="_blank"><?=$chreLink?> <small><i class="fa fa-external-link"></i></small></a>
          </td>
        </tr>
      <? endif; ?>

      <? $parallelEditions = $this->driver->getParallelEditions(); ?>
      <? if($parallelEditions): ?>
        <tr>
          <th><?=$this->transEsc('Other Editions')?>: </th>
          <td>
            <? foreach ($parallelEditions as $parallelEdition): ?>
              <a title="<?=$this->escapeHtml($parallelEdition['label'])?>" href="<?=$this->url('record', array('id' => $parallelEdition['id']))?>"><i class="fa fa-book"></i> <?=$this->escapeHtml($parallelEdition['label'])?></a><br/>
            <? endforeach; ?>
          </td>
        </tr>
      <? endif; ?>

      <? $seeAlsos = $this->driver->getSeeAlso(); ?>
      <? if($seeAlsos): ?>
        <tr>
          <th><?=$this->transEsc('See also')?>: </th>
          <td>
            <? foreach ($seeAlsos as $seeAlso): ?>
              <a title="<?=$this->escapeHtml($seeAlso['label'])?>" href="<?=$this->url('record', array('id' => $seeAlso['id']))?>"><i class="fa fa-book"></i> <?=$this->escapeHtml($seeAlso['label'])?></a><br/>
            <? endforeach; ?>
          </td>
        </tr>
      <? endif; ?>

      <? $childRecordCount = $this->driver->tryMethod('getChildRecordCount'); if ($childRecordCount): ?>
      <tr>
        <th><?=$this->transEsc('child_records')?>: </th>
        <td>
          <a href="<?=$this->recordLink()->getChildRecordSearchUrl($this->driver)?>"><i class="fa fa-folder-open"></i> <?=$this->transEsc('child_record_count', array('%%count%%' => $childRecordCount))?></i></a>
        </td>
      </tr>
      <? endif; ?>

      <?
        $openUrl = $this->openUrl($this->driver, 'record');
        $openUrlActive = $openUrl->isActive();
        // Account for replace_other_urls setting
        $urls = $this->record($this->driver)->getLinkDetails($openUrlActive);
      ?>
      <? if (!empty($urls) || $openUrlActive): ?>
      <tr>
        <th><?=$this->transEsc('Online Access')?>: </th>
        <td>
          <? foreach ($urls as $current): ?>
            <a href="<?=$this->escapeHtmlAttr($this->proxyUrl($current['url']))?>"><?=$this->escapeHtml($current['desc'])?></a><br/>
          <? endforeach; ?>
          <? if ($openUrlActive): ?>
            <?=$openUrl->renderTemplate()?><br/>
          <? endif; ?>
        </td>
      </tr>
      <? endif; ?>

      <? $additionalPhysicalFormNotes = $this->driver->getAdditionalPhysicalFormAvailableNote(); ?>
      <? if(!empty($additionalPhysicalFormNotes)): ?>
        <tr>
	 <th><?=$this->transEsc('Physical Form Note');?>: </th>
         <td>
           <? foreach ($additionalPhysicalFormNotes as $note): ?>
             <a href="<?= $note['uri']; ?>"><?= $note['label'];?>
           <? endforeach; ?>
         </td>
        </tr>
      <? endif; ?>


      <? $recordLinks = $this->driver->getAllRecordLinks(); ?>
      <? if(!empty($recordLinks)): ?>
        <tr>
          <th><?=$this->transEsc('Related Items')?>:</th>
          <td>
            <? foreach ($recordLinks as $recordLink): ?>
              <?=$this->transEsc($recordLink['title'])?>:
              <a href="<?=$this->recordLink()->related($recordLink['link'])?>"><?=$this->escapeHtml($recordLink['value'])?></a><br />
            <? endforeach; ?>
            <? /* if we have record links, display relevant explanatory notes */
              $related = $this->driver->getRelationshipNotes();
              if (!empty($related)): ?>
                <? foreach ($related as $field): ?>
                  <?=$this->escapeHtml($field)?><br/>
                <? endforeach; ?>
            <? endif; ?>
          </td>
        </tr>
      <? endif; ?>

      <? if ($this->usertags()->getMode() !== 'disabled'): ?>
        <? $tagList = $this->driver->getTags(null, null, 'count', $user_id); ?>
        <tr>
          <th><?=$this->transEsc('Tags')?>: </th>
          <td>
            <a id="tagRecord" class="btn btn-link modal-link pull-right flip" href="<?=$this->recordLink()->getActionUrl($this->driver, 'AddTag')?>" title="<?=$this->transEsc('Add Tag')?>">
              <i class="fa fa-plus"></i> <?=$this->transEsc('Add Tag')?></a>
            </a>
            <?=$this->context($this)->renderInContext('record/taglist', array('tagList'=>$tagList, 'loggedin'=>$loggedin)) ?>
          </td>
        </tr>
      <? endif; ?>
    </table>
    <?/* End Main Details */?>
  </div>

  <script src="/themes/archaeostrap/js/arachne-data.js"></script>
</div>
