<?
  // Set page title.
  $this->headTitle($this->translate('Search Home'));

  // Disable top search box -- this page has a special layout.
  $this->layout()->searchbox = false;

  // Set default value if necessary:
  if (!isset($this->searchClassId)) {
    $this->searchClassId = 'Solr';
  }

  // Load search actions and settings (if any):
  $options = $this->searchOptions($this->searchClassId);
  $basicSearch = $options->getSearchAction();
  $advSearch = $options->getAdvancedSearchAction();
  
  $this->layout()->breadcrumbs = false;
?>
<div class="searchHomeContent">
  <div class="home-image"></div>
  <h1 style="font-size: 60px; text-shadow: 0 1px 5px #000000; color:white; margin: -200px auto 120px;" class="text-center">
        iDAI.bilbiography / Zenon
  </h1>
  <? if ( $this->ils()->getOfflineMode() == "ils-offline"): ?>
    <div class="alert alert-warning">
      <h2><?=$this->transEsc('ils_offline_title')?></h2>
      <p><strong><?=$this->transEsc('ils_offline_status')?></strong></p>
      <p><?=$this->transEsc('ils_offline_home_message')?></p>
      <? $supportEmail = $this->escapeHtml($this->systemEmail()); ?>
      <p><a href="mailto:<?=$supportEmail?>"><?=$supportEmail?></a></p>
    </div>
  <? endif; ?>
  <div class="row-fluid">
    <div class="text-center span8 offset2 well">
      <?=$this->render("search/searchbox.phtml")?>
    </div>
  </div>
</div>

<div class="row-fluid">
  <hr />
</div>

<? $facetList = is_object($this->results) ? $this->results->getFacetList() : array(); ?>

<div class="row-fluid">

  <div class="span4 well">
    <? $libFacet = $facetList['building']; ?>
    <? if (!empty($libFacet)): ?>
      <? $sortedList = $this->sortFacetList($this->results, 'building', $libFacet['list'], $basicSearch); ?>
      <h4><?=$this->transEsc($libFacet['label'])?></h4>
      <div class="row-fluid">
        <div class="span6">
          <ul class="unstyled">
            <? foreach (array_slice($sortedList,0, 11) as $url => $value): ?>
              <li><a href="<?=$url?>"><?=$this->escapeHtml($value)?></a></li>
            <? endforeach; ?>
          </ul>
        </div>      
        <div class="span6">
          <ul class="unstyled">
            <? foreach (array_slice($sortedList,11, 11) as $url => $value): ?>
              <li><a href="<?=$url?>"><?=$this->escapeHtml($value)?></a></li>
            <? endforeach; ?>
          </ul>
        </div>
      </div>
    <? endif; ?>
  </div>
  <div class="span4 well">
    <h4>Zeitschriften</h4>
    <ul class="unstyled">
      <li><a href="<?=$this->url('search-results')?>?lookfor=daizss8&amp;type=Note">DAI-Zeitschriften</a></li>
      <li><a href="<?=$this->url('search-results')?>?lookfor=ejournal%20OR%20online&amp;type=Note">e-Publikationen</a></li>
    </ul>
  </div>
  <div class="span4 well">
    <h4>Neuerwerbungen</h4>
      <?
        $end = new DateTime("now +1 month");
        $start = new DateTime("now -2 year + 1 month");
        $interval = new DateInterval('P1M');
        $period = new DatePeriod($start, $interval, $end);
        $months = [];
      ?>
      <? foreach ($period as $dt): ?>
        <?
          $queryMonth = $dt->format('my');
          $queries = [];
          foreach(['a','e','i','k','c','m','o','f','r','z'] as $char) $queries[] = $char.$queryMonth;
          $query = join(' OR ', $queries);
          $months[] = array("date" => $dt, "query" => $query);
        ?>
      <? 
        endforeach;
        $months = array_reverse($months)
      ?>
    <div class="row-fluid">
      <div class="span6">
        <ul class="unstyled">
          <? foreach (array_slice($months,0,12) as $month): ?>
            <li>
              <a href="<?=$this->url('search-results')?>?lookfor=<?=$month["query"]?>&amp;type=Note">
                <?=$this->transEsc($month["date"]->format('F'))?> <?=$month["date"]->format('Y')?>
              </a>
            </li>
          <? endforeach; ?>
        </ul>
      </div>      
      <div class="span6">
        <ul class="unstyled">
          <? foreach (array_slice($months,12,12) as $month): ?>
            <li>
              <a href="<?=$this->url('search-results')?>?lookfor=<?=$month["query"]?>&amp;type=Note">
                <?=$this->transEsc($month["date"]->format('F'))?> <?=$month["date"]->format('Y')?>
              </a>
            </li>
          <? endforeach; ?>
        </ul>
      </div>
    </div>

    <ul class="unstyled">
    </ul>

  </div>
</div>
