<? if (!isset($this->indexStart)) $this->indexStart = 0; ?>
<? $i = $this->indexStart; ?>
<? foreach ($this->results->getResults() as $current): ?>
  <? $recordNumber = $this->results->getStartRecord() + $i-$this->indexStart; ?>
  <h3>
    <? if (isset($this->showCheckboxes) && $this->showCheckboxes): ?>
    <label>
        <?=$this->record($current)->getCheckbox('', 'search-cart-form')?>
        <?=$recordNumber ?>
    </label>
    <? else: ?>
        <?=$recordNumber ?>
    <? endif; ?>
  </h3>
  <div id="result<?=$i++ ?>" class="result<?=$current->supportsAjaxStatus()?' ajaxItem':''?>">
    <div>
    <?=$this->record($current)->getSearchResult('list-cite') ?>
    </div>
  </div>
<? endforeach; ?>
