<? if (!isset($this->indexStart)) $this->indexStart = 0; ?>
<? $i = $this->indexStart; ?>

<h1><?=$this->transEsc('Cite this')?></h1>
<p>
<div class="container">
<? foreach ($this->results->getResults() as $current): ?>
  <div class="row" <?= ($i != 0) ? 'style="border-top: 1px solid #000;"' : '' ?>>
    <? $recordNumber = $this->results->getStartRecord() + $i-$this->indexStart; ?>
    <?=$this->record($current)->getSearchResult('list-cite') ?>
  </div>
<?$i++ ?>
<? endforeach; ?>
</div>