<? if (count($searchTabs) > 0): ?>

<div class="btn-group">
  <button type="button" class="btn btn-default dropdown-toggle"
  data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
    <span class="caret"></span> 
    <? foreach ($searchTabs as $tab): ?>
      <? if($tab['selected']): ?>
            <?= $this->transEsc($tab['label']); ?>
      <? endif ?>
    <? endforeach; ?> <i class="fa fa-eye" aria-hidden="true"></i>
  </button>
  <ul class="dropdown-menu">
    <? foreach ($searchTabs as $tab): ?>
      <? if($tab['selected']): ?>
        <li>
          <a> <?= $this->transEsc($tab['label']); ?> <i class="fa fa-eye" aria-hidden="true"></i></a>
        </li>
      <? else: ?>
        <li>
          <a href="<?= $this->escapeHtmlAttr($tab['url']);?>">
            <?= $this->transEsc($tab['label']); ?>
          </a>
        </li>
      <? endif ?>
    <? endforeach; ?>
  </ul>
</div>
<? endif; ?>
