<?=$this->doctype('HTML5')?>
<html lang="<?=$this->layout()->userLang?>">
  <head>
    <meta name="viewport" content="width=device-width,initial-scale=1.0"/>
    <?$this->headThemeResources()?>
    <?=$this->headMeta()?>
    <?=$this->headTitle()?>
    <?
      // Set up OpenSearch link:
      $this->headLink(
        array(
          'href' => $this->url('search-opensearch') . '?method=describe',
          'type' => 'application/opensearchdescription+xml',
          'title' => $this->transEsc('Library Catalog Search'),
          'rel' => 'search'
        )
      );
    ?>
    <?=$this->headLink()?>
    <?=$this->headStyle()?>
    <?
        // Set global path for Javascript code:
        $this->headScript()->prependScript("path = '" . rtrim($this->url('home'), '/') . "';");

        // Deal with cart stuff:
        if (!isset($this->renderingError)) {
            $cart = $this->cart();
            $this->jsTranslations()->addStrings(
                array(
                    'bulk_email_success' => 'bulk_email_success',
                    'bulk_save_success' => 'bulk_save_success',
                    'close' => 'close',
                    'loading' => 'Loading',
                    'sms_success' => 'sms_success'
                )
            );
            if ($cart->isActive()) {
                $this->headScript()->appendFile("cookies.js");
                $this->headScript()->appendFile("cart.js");
                $this->jsTranslations()->addStrings(
                    array(
                        'bulk_noitems_advice' => 'bulk_noitems_advice',
                        'confirmEmpty' => 'bookbag_confirm_empty',
                        'viewBookBag' => 'View Book Bag',
                        'addBookBag' => 'Add to Book Bag',
                        'removeBookBag' => 'Remove from Book Bag',
                        'itemsAddBag' => 'items_added_to_bookbag',
                        'itemsInBag' => 'items_already_in_bookbag',
                        'bookbagMax' => $cart->getMaxSize(),
                        'bookbagFull' => 'bookbag_full_msg',
                        'bookbagStatusFull' => 'bookbag_full',
                    )
                );
            }
            $this->headScript()->appendScript($this->jsTranslations()->getScript());
        }
        
        // Session keep-alive
        if ($this->KeepAlive()) {
            $this->headScript()->appendScript('var keepAliveInterval = '
                . $this->KeepAlive());
            $this->headScript()->appendFile("keep_alive.js");
        }

	$this->headScript()->appendScript('$(document).ready(function(){$("#affix-menu").affix({ offset: {top: 176} })});');

    ?>
    <?=$this->headScript()?>
  </head>
  <body>
    <div class="container">
      <div class="archaeo-fixed-menu">
        <div id="header" class="clearfix noprint">
          <?=$this->render('header.phtml')?>
        </div>
        <div class="affix-menu-wrapper">
          <div id="affix-menu" style="z-index: 100000" class="navbar navbar-inverse container affix-top" data-spy="affix">
            <div class="navbar-inner">
              <div id="archaeo-fixed-menu-icon"></div>
              <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse"> <span class="icon-bar"></span> <span class="icon-bar"></span> <span class="icon-bar"></span></a>
              <a class="brand" href="">iDAI.bibliography / Zenon</a>
              <? // Set up the search box -- there are three possible cases:
                 // 1. No search box was set; we should default to the normal box
                 // 2. It was set to false; we should display nothing
                 // 3. It is set to a custom string; we should display the provided version
                 // Set up default search box if no data was provided from the template;
                 // this covers case 1.  Cases 2 and 3 are then covered by logic below.
                if (!isset($this->layout()->searchbox)) {
                  $this->layout()->searchbox = $this->render('search/searchbox.phtml');
                }
              ?>
              <? if ($this->layout()->searchbox !== false): ?>
                <div class="searchbox noprint pull-left">
                  <?=$this->layout()->searchbox?>
                </div>
              <? else: ?>

                <a class="btn btn-link" style="color: #fcfcfc; text-shadow: 0 -1px 0 rgba(0, 0, 0, 0.25);" href="<?=$this->url("search-advanced")?>"><?=$this->transEsc("Advanced Search")?></a>
                
              <? endif; ?>
              <ul class="nav pull-right">
                <li class="dropdown">
                  <a href="#" class="dropdown-toggle" data-toggle="dropdown">iDAI.welt <b class="caret"></b></a>
                  <ul class="dropdown-menu">
                    <li><a href="http://www.dainst.org/de/forschung/forschung-digital/idai.welt" target="_blank">Übersicht</a></li>
                    <li class="divider"></li>
                    <li><a href="https://gazetteer.dainst.org/" target="_blank">iDAI.gazetteer</a></li>
                    <li><a href="http://geoserver.dainst.org/" target="_blank">iDAI.geoserver</a></li>
                    <li><a href="http://arachne.uni-koeln.de/" target="_blank">iDAI.objects / Arachne</a></li>
                    <li><a href="http://hellespont.dainst.org" target="_blank">Hellespont</a></li>
                  </ul>
                </li>
              </ul>
            </div>
          </div>
        </div>
      </div>
      
      <? if((!isset($this->layout()->showBreadcrumbs) || $this->layout()->showBreadcrumbs == true)
        && !empty($this->layout()->breadcrumbs)
        && $this->layout()->breadcrumbs !== false
      ): ?>
        <ul class="breadcrumb">
        <? if(is_array($this->layout()->breadcrumbs)): ?>
          <? if(count($this->layout()->breadcrumbs) > 1): ?>
            <?=$this->render('breadcrumbs/multi.phtml', array(
                'parents' => $this->layout()->breadcrumbs,
                'title'   => $this->layout()->title,
                'end'     => $this->layout()->breadcrumbEnd,
                'from'    => $this->layout()->from
              )) ?>
          <? else: ?>
            <?=$this->render('breadcrumbs/default.phtml', array(
                'parents' => $this->layout()->breadcrumbs,
                'title'   => $this->layout()->title
              )) ?>
          <? endif; ?>
        <? else: ?>
          <?=$this->layout()->breadcrumbs ?>
        <? endif; ?>
        </ul>
      <? endif; ?>
      <div class="main row-fluid">
        <?=$this->layout()->content?>
      </div>
      <div class="footer noprint">
        <?=$this->render('footer.phtml')?>
        <?=$this->layout()->poweredBy?>
      </div>
    </div>
    <!-- MODAL IN CASE WE NEED ONE -->
    <div id="modal" class="modal hide fade">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        <h3></h3>
      </div>
      <div class="modal-body"><?=$this->transEsc('Loading') ?>...</div>
    </div>
    <?=$this->googleanalytics()?>
  </body>
</html>
