<?
// Set up convenience variables:
$account = $this->auth()->getManager();
$user = $account->isLoggedIn();
$openUrl = $this->openUrl($this->driver, 'holdings');
$openUrlActive = $openUrl->isActive();
// Account for replace_other_urls setting
$urls = $this->record($this->driver)->getLinkDetails($openUrlActive);
$offlineMode = $this->ils()->getOfflineMode();
try {
    $holdings = $this->driver->getRealTimeHoldings();
} catch (\VuFind\Exception\ILS $e) {
    $holdings = ['holdings' => []];
    $offlineMode = 'ils-offline';
}
// Set page title.
$this->headTitle($this->translate('Holdings') . ': ' . $this->driver->getBreadcrumb());
?>

<?=$this->context($this)->renderInContext('librarycards/selectcard.phtml', ['user' => $this->auth()->isLoggedIn()]); ?>

<? if (!empty($holdings['blocks'])):?>
    <div id="account-block-msg" class="alert alert-danger">
        <?=$this->transEsc('account_block_options_missing', ['%%details%%' => implode('; ', $holdings['blocks'])]) ?>
    </div>
<? endif; ?>

<?=($offlineMode == "ils-offline") ? $this->render('Helpers/ils-offline.phtml', ['offlineModeMsg' => 'ils_offline_holdings_message']) : ''?>
<? if (($this->ils()->getHoldsMode() == 'driver' && !empty($holdings['holdings'])) || $this->ils()->getTitleHoldsMode() == 'driver'): ?>
    <? if ($account->loginEnabled() && $offlineMode != 'ils-offline'): ?>
        <? if (!$user): ?>
            <div class="alert alert-info">
                <a href="<?=$this->recordLink()->getTabUrl($this->driver, 'Holdings')?>?login=true&amp;catalogLogin=true" data-lightbox><?=$this->transEsc("hold_login")?></a>
            </div>
        <? elseif (!$user->cat_username): ?>
            <div class="alert alert-info">
                <?=$this->translate("hold_profile_html", ['%%url%%' => $this->recordLink()->getTabUrl($this->driver, 'Holdings') . '?catalogLogin=true'])?>
            </div>
        <? endif; ?>
    <? endif; ?>
<? endif; ?>
<? $holdingTitleHold = $this->driver->tryMethod('getRealTimeTitleHold'); if (!empty($holdingTitleHold)): ?>
    <a class="placehold" data-lightbox title="<?=$this->transEsc('request_place_text')?>" href="<?=$this->recordLink()->getRequestUrl($holdingTitleHold)?>"><i class="fa fa-flag" aria-hidden="true"></i>&nbsp;<?=$this->transEsc('title_hold_place')?></a>
<? endif; ?>
<? if (!empty($urls) || $openUrlActive): ?>
        <? if (!empty($urls)): ?>
            <? foreach ($urls as $current): ?>
                <?
                $url = $this->proxyUrl($current['url']);
                if(strcmp(substr($url, 0, 4 ), "wwww.") == 0) {
                    $url = "http://" . $url;
                }
                ?>
                <a  class="btn btn-block" role="button" href="<?= $url ?>" target="_blank"><?=$this->escapeHtml($current['desc'])?></a><br/>
            <? endforeach; ?>
        <? endif; ?>
        <? if ($openUrlActive): ?><?=$openUrl->renderTemplate()?><? endif; ?>
<? endif; ?>
<? foreach ($holdings['holdings'] as $holding): ?>
    <? $toggleTargetId = 'collapse' . str_replace([' ', '/'],'',$holding['location']); ?>
    <a  class="btn btn-zenon-default btn-block" role="button" data-toggle="collapse" href="#<?= $toggleTargetId; ?>" aria-expanded="false" aria-controls="collapse-group">
        <? $locationText = $this->transEsc('location_' . $holding['location'], [], $holding['location']); ?>
        <? if (isset($holding['locationhref']) && $holding['locationhref']): ?>
            <a href="<?=$holding['locationhref']?>" target="_blank"><?=$locationText?></a>
        <? else: ?>
            <?= $locationText ?>
        <? endif; ?>
    </a>

    <? usort($holding['items'], function($a, $b) { return strcmp($a['summary'], $b['summary']); } ); ?>
    <div class="collapse" id="<?= $toggleTargetId; ?>">
        <table class="table table-striped" summary="<?=$this->transEsc('holdings_details_from', ['%%location%%' => $this->transEsc($holding['location'])]) ?>">
            <tr>
                <th width="25%"><?=$this->transEsc("Call Number")?></th>
                <th width="25%"><?= $this->transEsc("holdings::Description") ?></th>
                <th width="25%"><?= $this->transEsc("holdings::Item Status") ?></th>
                <th width="25%"><?= $this->transEsc("holdings::Notes") ?></th>
            </tr>
            <? foreach ($holding['items'] as $row): ?>

                <? if (!(empty($row['callnumber']) && empty($row['summary']) && empty($row['status']) && empty($row['notes']))): ?>
                    <tr>
                        <td><?=$this->transEsc($row['callnumber'])?></td>
                        <td><?=$this->transEsc($row['summary'])?></td>
                        <td><?=$this->transEsc($row['status'])?></td>
                        <td><?=$this->transEsc($row['notes'])?></td>
                    </tr>
                <? endif; ?>
            <? endforeach; ?>
        </table>
    </div>
<? endforeach; ?>

<? $history = $this->driver->getRealTimeHistory(); ?>
<? if (is_array($history) && !empty($history)): ?>
    <h3><?=$this->transEsc("Most Recent Received Issues")?></h3>
    <table class="table table-striped">
        <? foreach ($history as $row): ?>
            <tr><td><?=$this->escapeHtml($row['issue'])?></td></tr>
        <? endforeach; ?>
    </table>
<? endif; ?>
