<?
    // Set up convenience variables:
    $account = $this->auth()->getManager();
    $user = $account->isLoggedIn();
    $holdings = $this->driver->getRealTimeHoldings();
    $openUrl = $this->openUrl($this->driver, 'holdings');
    $openUrlActive = $openUrl->isActive();
    // Account for replace_other_urls setting
    $urls = $this->record($this->driver)->getLinkDetails($openUrlActive);
    $offlineMode = $this->ils()->getOfflineMode();
    // Set page title.
    $this->headTitle($this->translate('Holdings') . ': ' . $this->driver->getBreadcrumb());
?>

<?=$this->context($this)->renderInContext('librarycards/selectcard.phtml', array('user' => $this->auth()->isLoggedIn())); ?>

<? if ($offlineMode == "ils-offline"): ?>
  <div class="alert alert-warning">
    <h2><?=$this->transEsc('ils_offline_title')?></h2>
    <p><strong><?=$this->transEsc('ils_offline_status')?></strong></p>
    <p><?=$this->transEsc('ils_offline_holdings_message')?></p>
    <? $supportEmail = $this->escapeHtmlAttr($this->systemEmail()); ?>
    <p><a href="mailto:<?=$supportEmail?>"><?=$supportEmail?></a></p>
  </div>
<? endif; ?>
<? if (($this->ils()->getHoldsMode() == 'driver' && !empty($holdings)) || $this->ils()->getTitleHoldsMode() == 'driver'): ?>
  <? if ($account->loginEnabled() && $offlineMode != 'ils-offline'): ?>
    <? if (!$user): ?>
      <div class="alert alert-info">
        <a href="<?=$this->recordLink()->getTabUrl($this->driver, 'Holdings')?>?login=true&amp;catalogLogin=true"><?=$this->transEsc("Login")?></a> <?=$this->transEsc("hold_login")?>
      </div>
    <? elseif (!$user->cat_username): ?>
      <div class="alert alert-info">
        <?=$this->translate("hold_profile_html", array('%%url%%' => $this->recordLink()->getTabUrl($this->driver, 'Holdings') . '?catalogLogin=true'))?>
      </div>
    <? endif; ?>
  <? endif; ?>
<? endif; ?>
<? $holdingTitleHold = $this->driver->tryMethod('getRealTimeTitleHold'); if (!empty($holdingTitleHold)): ?>
    <a class="placehold modal-link" title="<?=$this->transEsc('request_place_text')?>" href="<?=$this->recordLink()->getRequestUrl($holdingTitleHold)?>"><i class="fa fa-flag"></i>&nbsp;<?=$this->transEsc('title_hold_place')?></a>
<? endif; ?>
<? if (!empty($urls) || $openUrlActive): ?>
  <h3><?=$this->transEsc("Internet")?></h3>
  <? if (!empty($urls)): ?>
    <? foreach ($urls as $current): ?>
      <a href="<?=$this->escapeHtmlAttr($this->proxyUrl($current['url']))?>"><?=$this->escapeHtml($current['desc'])?></a><br/>
    <? endforeach; ?>
  <? endif; ?>
  <? if ($openUrlActive): ?><?=$openUrl->renderTemplate()?><? endif; ?>
<? endif; ?>
<? foreach ($holdings as $holding): ?>
<h3>
  <? $locationText = $this->transEsc('location_' . $holding['location'], array(), $holding['location']); ?>
  <? if (isset($holding['locationhref']) && $holding['locationhref']): ?>
    <a href="<?=$holding['locationhref']?>" target="_blank"><?=$locationText?></a>
  <? else: ?>
    <?=$locationText?>
  <? endif; ?>
</h3>

<? /* neue Bestandsanzeige: Tabelle, die Zeile für Zeile die Daten aus MARC 993 anzeigt */ ?>
<table class="table table-striped" summary="<?=$this->transEsc('Holdings details from')?> <?=$this->transEsc($holding['location'])?>">
    <tr><th><?=$this->transEsc("Call Number")?>:</th><th><?=$this->transEsc("holdings::Description")?>:</th><th><?=$this->transEsc("holdings::Item Status")?>:</th><th><?=$this->transEsc("holdings::Notes")?>:</th></tr>

<? usort($holding['items'], function($a, $b) {return $b['summary'] - $a['summary'];} ); ?>
<? foreach ($holding['items'] as $item): ?>
  <? if (!(empty($item['callnumber']) && empty($item['summary']) && empty($item['status']) && empty($item['summary']))): ?>
    <tr vocab="http://schema.org/" typeof="Offer"><link property="availability" href="http://schema.org/InStoreOnly" />
      <td><?=$this->escapeHtml($item['callnumber'])?></td>
      <td><?=$this->escapeHtml($item['summary'])?></td>
      <td><?=$this->escapeHtml($item['status'])?></td>
      <td><?=$this->escapeHtml($item['notes'])?></td>
      <? if ($item['location']): ?>
        <meta property="seller" content="<?=$this->escapeHtmlAttr($item['location'])?>" />
      <? endif; ?>
      <? if ($item['callnumber']): ?>
        <meta property="sku" content="<?=$this->escapeHtmlAttr($item['callnumber'])?>" />
      <? endif; ?>
      <? /* Declare that the item is to be borrowed, not for sale */ ?>
      <link property="businessFunction" href="http://purl.org/goodrelations/v1#LeaseOut" />
      <link property="itemOffered" href="#record" />
    </tr>
  <? endif; ?>
<? endforeach; ?>
</table>

<? endforeach; ?>

