<?
    $marc = $this->driver->tryMethod('getMarcRecord');
    if (is_object($marc)) {
        $marcPhdField = $marc->getField('502');
    }
    $journalTitle = $this->driver->tryMethod('getContainerTitle');
    $formats = $this->driver->tryMethod('getFormats');
    if ($marcPhdField) {
        $format = 'thesis';
    } else if (!empty($journalTitle) || (is_array($formats) && in_array('Article', $formats))) {
        $format = 'article';
    } else {
        $format = 'book';
    }

    $zenonId = $this->driver->getUniqueId();
    $title = rtrim($this->driver->getShortTitle(), " /;.,:");
    $authors = $this->driver->tryMethod('getDeduplicatedAuthors')['primary'];
    $languages = $this->driver->tryMethod('getLanguages');
    $pubDates = $this->driver->tryMethod('getPublicationDates');
    $pubPlaces = $this->driver->tryMethod('getPlacesOfPublication');
    $pubNames = $this->driver->tryMethod('getPublishers');
?>
{"id": "<?= $zenonId; ?>"
<? if($format): ?>
,"type": "<?= $format; ?>"
<? endif ?>
<? if($title): ?>
,"title": "<?= $title; ?>"
<? endif ?>
<? if(!empty($pubNames)): ?>
,"publisher": "<?= rtrim(implode('/', $pubNames), ',') ?>"
<? endif ?>
<? if(!empty($pubPlaces)): ?>
,"publisher-place": "<?= rtrim(implode('/', $pubPlaces), ',') ?>"
<? endif ?>
<? if(!empty($authors)): ?>
,"author":[
<? $counter = 0 ?>
<? foreach ($authors as $key => $value): ?>
<? $split = explode(',', $key) ?>
<? if($counter != 0):?>,<?endif?>{"family": "<?= trim($split[0]) ?>"<? if(count($split) > 1): ?>, "given": "<?= trim($split[1]) ?>"<? endif ?>}
<? $counter += 1 ?>
<? endforeach ?>
]
<? endif ?>
<? if(!empty($pubDates)): ?>
,"issued": {
"raw":"<?= implode('/', $pubDates) ?>"
<? endif ?>
}
}