<h1>Info E-Ressourcen des DAI</h1>

<h2>Allgemein</h2>

<p>
In iDAI.bibliography / ZENON  können Sie unseren Literaturbestand, egal ob es sich um gedruckte oder digital publizierte Literatur handelt, finden. Entsprechend der Erscheinungsform (print oder digital) gibt Ihnen der Katalog Auskunft über den Standort des Mediums anhand der Signatur oder ermöglicht Ihnen den direkten Zugriff auf den digitalen Volltext.
</p>
<p>
Alle lizenzierten Datenbanken, E-Books und E-Journals sind aus dem IP-Netz der Standorte des DAI frei zugänglich.
</p>

<h3 id="terms-of-use">Nutzungsbedingungen</h3>

<p>
Für die Nutzung von kostenpflichtigen elektronischen Angeboten wie elektronische Zeitschriften, Datenbanken und E-Books gelten besondere Bedingungen. Es gelten die urheberrechtlichen Bestimmungen und die AGBs der jeweiligen Anbieterplattformen. Der Zugriff setzt die Einhaltung der Nutzungsbedingungen voraus.
</p>
<p>
Generell gilt:
</p>
<p>
Die Nutzung der E-Ressourcen ist nur zum persönlichen Gebrauch und zu wissenschaftlichen Zwecken erlaubt. Eine kommerzielle Nutzung bzw. Verwertung ist nicht gestattet. Eine Weitergabe der Inhalte an Dritte, z. B. in Form von Ausdrucken oder Downloads, ist nicht zulässig. 
</p>
<p>
Es dürfen in der Regel nur kleine Mengen wie einzelne Seiten oder Artikel bzw. Kapitel der abgespeichert oder ausgedruckt werden. Der systematische Download oder Ausdruck größerer Datenmengen ist nicht gestattet. Der Einsatz von Programmen zum fortlaufenden automatischen Durchsuchen, Indexieren oder Herunterladen der Inhalte (wie z. B. Web-Crawling-, Spider- oder Download-Programme) oder andere Handlungen, die die Systeme der Anbieter über die übliche Nutzung hinausgehend belasten, sind nicht gestattet. Bei Zuwiderhandeln droht die dauerhafte Abschaltung des Online-Zuganges  für das ganze DAI, da die Anbieter die Downloadraten bzw. –mengen mit technischen Mitteln überwachen.
</p>

<hr>

<h2>Elektronische Zeitschriften (eJournals)</h2>

<p>
Bitte verwenden Sie für die Recherche nach elektronischen Zeitschriften Die EZB. Die Elektronische Zeitschriftenbibliothek (<a onclick="window.open('http://www.ezb.uni-regensburg.de/', '_blank');">EZB</a>) bietet einen schnellen und strukturierten Zugang zu wissenschaftlichen Zeitschriften aller Fachgebiete. Durch ein Ampelsystem können Sie erkennen, ob die gesuchte Zeitschrift für das DAI freigeschaltet ist.
</p>

<h3>Anleitung: Wie finde ich elektronische Zeitschriften in der EZB?</h3>

<p>
Die EZB finden Sie unter dem Link <a onclick="window.open('http://ezb.uni-regensburg.de', '_blank');">http://ezb.uni-regensburg.de</a> Überprüfen Sie zunächst, ob Sie sich auf der EZB-Oberfläche des DAI befinden:
</p>

<img class="screenshot" src="/themes/archaeostrap/images/e-resources/screenshot_ejournals_1.png"></img>

<p>
Innerhalb der Räumlichkeiten des DAI ist dies in der Regel der Fall. Wenn Sie die EZB von zu Hause aus aufrufen, rufen Sie erst die EZB-Oberfläche des DAI auf. Wählen Sie dazu in der linken Spalte den Punkt „Bibliothek auswählen“ aus:
</p>

<img class="screenshot" src="/themes/archaeostrap/images/e-resources/screenshot_ejournals_2.png"></img>

<p>
Wählen Sie das Deutsche Archäologische Institut aus, je nach Standort befindet es sich im Drop-Down-Menü unter „Deutschland“ oder unter „andere Länder“. 
</p>

<img class="screenshot" src="/themes/archaeostrap/images/e-resources/screenshot_ejournals_3.png"></img>

<p>
Nachdem Sie die Einrichtung ausgewählt haben, befinden Sie sich wieder auf der Startseite und Sie können mit Ihrer Recherche beginnen:
</p>

<img class="screenshot" src="/themes/archaeostrap/images/e-resources/screenshot_ejournals_4.png"></img>

<p>
Hier ein Beispiel für ein Suchergebnis. Es werden drei Treffer angezeigt, da wir über drei verschiedene Lizenzmodelle Zugriff auf diese Zeitschrift haben. Klicken Sie auf „Zu den Volltexten“, um zum Volltext auf die Website des Anbieters zu gelangen. 
</p>

<img class="screenshot" src="/themes/archaeostrap/images/e-resources/screenshot_ejournals_5.png"></img>

<p>
Die Zugänglichkeit der Zeitschriften wird Ihnen mit einem Ampelsystem angezeigt. Auf der Startseite der EZB können Sie die Zeitschriften auch nach Ihrer Zugangsart eingrenzen: 
</p>

<img class="screenshot" src="/themes/archaeostrap/images/e-resources/screenshot_ejournals_6.png"></img>

<p>
Alle lizenzierten eJournals sind innerhalb der Räumlichkeiten des DAI frei zugänglich. Beachten Sie bitte vor der Nutzung die <a href="#terms-of-use">Nutzungsbedingungen</a>.
</p>

<hr>

<h2>Datenbanken – Fachbibliographien</h2>

<p>
Das Datenbank-Infosystem (DBIS) bietet Zugriff auf eine Vielzahl von Fachdatenbanken, die wir lizenziert haben oder die über das Internet kostenfrei verfügbar sind. In diesen Fachdatenbanken können Sie Literaturrecherchen durchführen oder Fakten bzw. Volltexte abrufen.
</p>

</p>
In DBIS ermitteln Sie zunächst, über die Übersicht nach Fachgebieten, die alphabetische Liste oder die Suchfunktion, die für Ihr Thema oder Ihre Recherche einschlägigen Datenbanken. In vielen Fällen ist auch der direkte Zugriff auf Volltexte der Aufsätze, E-Books und Dokumente möglich. In DBIS finden Sie auch elektronische Zeitungen.
</p>

<h3>Anleitung: Wie finde ich Datenbanken in DBIS?</h3>

<p>
Das DBIS finden Sie unter dem Link <a onclick="window.open('https://dbis.uni-regensburg.de/dbinfo/fachliste.php', '_blank');">https://dbis.uni-regensburg.de/dbinfo/fachliste.php</a>
</p>

<p>
Überprüfen Sie zunächst, ob Sie sich auf der DBIS-Oberfläche des DAI befinden:
</p>

<img class="screenshot" src="/themes/archaeostrap/images/e-resources/screenshot_dbis_1.png"></img>
 
<p>
Innerhalb der Räumlichkeiten des DAI ist dies in der Regel der Fall. Wenn Sie die DBIS von zu Hause aus aufrufen, rufen Sie erst die DBIS-Oberfläche des DAI auf. Wählen Sie dazu in der linken Spalte den Punkt „Bibliotheksauswahl / Einstellungen“ aus:
</p>
 
<img class="screenshot" src="/themes/archaeostrap/images/e-resources/screenshot_dbis_2.png"></img>
 
<p>
Wählen Sie das Deutsche Archäologische Institut aus, es befindet sich relativ weit oben im Drop-Down-Menü:
</p>
 
<img class="screenshot" src="/themes/archaeostrap/images/e-resources/screenshot_dbis_3.png"></img>

<p>
Nachdem Sie die Einrichtung ausgewählt haben, befinden Sie sich wieder auf der Startseite und Sie können mit Ihrer Recherche beginnen:
</p>

<img class="screenshot" src="/themes/archaeostrap/images/e-resources/screenshot_dbis_4.png"></img>

<p>
Die Art der Zugänglichkeit der Datenbanken können Sie eingrenzen. Gehen Sie dazu zum Punkt „Bibliotheksauswahl / Einstellungen“ in der linken Leiste.
</p>

<img class="screenshot" src="/themes/archaeostrap/images/e-resources/screenshot_dbis_5.png"></img>

<p>
Alle lizenzierten Datenbanken sind innerhalb der Räumlichkeiten des DAI frei zugänglich. Beachten Sie bitte vor der Nutzung die <a href="#terms-of-use">Nutzungsbedingungen</a>.
</p>

<hr>

<h2>eBooks</h2>

<p>
In <a onclick="window.open('https://zenon.dainst.org', '_blank');">iDAI.bibliography / ZENON</a> finden Sie eBooks genauso wie herkömmliche Bücher. Sie sind mittels Autor-/ Titelrecherche etc. auffindbar. eBooks erkennen Sie an dem Hinweis "Available online" in der Trefferliste. Haben Sie ein eBook gefunden, können Sie über den Link „Available online“ auf das eBook zugreifen.
</p>

<p>
Hier ein Beispiel für ein eBook-Ergebnis in Zenon:
</p>

<img class="screenshot" src="/themes/archaeostrap/images/e-resources/screenshot_zenon_1.png"></img>
 
<p>
Um gezielt nach eBooks zu suchen, können Sie die erweiterte Suche in Zenon nutzen.
Zum Beispiel:
</p>

<img class="screenshot" src="/themes/archaeostrap/images/e-resources/screenshot_zenon_2.png"></img>

<p>
Alle lizenzierten eBooks sind innerhalb der Räumlichkeiten des DAI frei zugänglich. Beachten Sie bitte vor der Nutzung die <a href="#terms-of-use">Nutzungsbedingungen</a>.
</p>

<p>
Das DAI hat eBooks unterschiedlicher Anbieter lizenziert oder erworben. Da sich noch keine allgemeinverbindlichen Standards für E-Books durchgesetzt haben, gibt es bisher kein einheitliches Format und auch keine einheitlichen Zugriffsmöglichkeiten. So können Sie E-Books manchmal als Ganzes auf Ihrem Rechner speichern, in vielen Fällen in Teilen, etwa als einzelne Seite oder als einzelnes Kapitel. Bei einigen Anbietern gibt es aus lizenzrechtlichen Gründen leicht eingeschränkte Nutzungsmöglichkeiten.
</p>

<h3>Benutzungshinweise der Plattform Ebook Central von ProQuest</h3>

<p>
Ebook Central ist eine Plattform mit eBooks von verschiedenen Verlagen. Die Nutzung dieser eBooks unterliegt gewissen Nutzungs-Einschränkungen, um das DRM (Digital Rights Management) zu gewährleisten.
</p>
<p>
Hier ein Beispiel für eBook auf der Plattform Ebook Central:
</p>
<img class="screenshot" src="/themes/archaeostrap/images/e-resources/screenshot_proquest_1.png"></img>

<p>
Online lesen ist ohne Einschränkung möglich.
</p>

<p>
Mit der Funktion „Vollständiger Download“ können Sie das eBook für 3 Tage auf Ihrem Endgerät abspeichern. Dafür benötigen Sie die (kostenlose) Software „Adobe Digital Editions“. (Für mobile Endgeräte benötigen Sie den BlueFire Reader.) Nach den 3 Tagen können Sie das eBook nicht mehr öffnen, während dieser 3 Tage ist das eBook für andere Interessenten nicht zugänglich. Deswegen ist der Kapitel-Download empfehlenswerter.
</p>

<p>
Kapitel herunterladen: Sie können einen gewissen Prozentsatz der Seiten eines eBooks downloaden bzw. drucken. Ebenso können Sie mit der Kopierfunktion einige Seiten aus dem PDF herauskopieren. Die Anzahl dieser Seiten wird für jedes eBook angezeigt. Wenn das "Guthaben" für Download/Druck bzw. Kopieren aufgebraucht ist, können Sie nach einer Wartezeit von 24 Stunden wieder auf dieselbe Anzahl von Seiten zugreifen. Diese heruntergeladenen Anteile können Sie dauerhaft speichern.
</p>

<hr>

<h2>Nationallizenzen</h2>

<p>
Zur nachhaltigen Verbesserung der wissenschaftlichen Literaturversorgung unterstützt die Deutsche Forschungsgemeinschaft (<a onclick="window.open('https://www.dfg.de/index.jsp', '_blank');">DFG</a>)  den Erwerb von Nationallizenzen für digitale Publikationen. Die Lizenzen gelten für alle deutschen Hochschulen und alle mit öffentlichen Mitteln finanzierten deutschen Forschungseinrichtungen. Sie umfassen Publikationen verschiedener Verlage und Fachgesellschaften. Es gibt Nationallizenzen für Bibliographische Datenbanken, elektronische Zeitschriften, Datenbanken, eBooks und Nachschlagewerke. Eine Übersicht über die Nationallizenzen finden Sie auf der Seite der Nationallizenzen unter Angebote: <a onclick="window.open('https://www.nationallizenzen.de/angebote', '_blank');">https://www.nationallizenzen.de/angebote oder die entsprechenden Übersichtsseiten in DBIS:
</p>
<p>
<a onclick="window.open('https://dbis.uni-regensburg.de/dbinfo/detail.php?titel_id=6603&bib_id=dai', '_blank');"> Nationallizenzen / Sammlungen - Monographien</a>
<a onclick="window.open('https://dbis.uni-regensburg.de/dbinfo/detail.php?titel_id=7036&bib_id=dai', '_blank');">
Nationallizenzen / Sammlungen - Zeitschriften</a>
</p>

<p>
Zeitschriften aus den Nationallizenzen sind in die <a onclick="window.open('http://ezb.uni-regensburg.de/', '_blank');">EZB</a> integriert. Wenn Sie also in der EZB nach Zeitschriften suchen, erhalten Sie automatisch auch Treffer aus dem Angebot der Nationallizenzen. Die Inhalte aus den Nationallizenzen sind teilweise auch in Zenon integriert.
</p>

<p>
Wenn Sie von außerhalb des DAI hierauf zugreifen möchten, können Sie sich für manche Nationallizenzen als Einzelnutzer registrieren lassen: <a onclick="window.open('https://www.nationallizenzen.de/ind_inform_registration', '_blank');">https://www.nationallizenzen.de/ind_inform_registration</a>
</p>

<hr>

<h2>Zeitschriftenarchiv JSTOR</h2>

<p>
Durch finanzielle Unterstützung der DFG konnte das DAI das elektronische Zeitschriftenarchiv JSTOR ("Journal Storage") lizenzieren. Hierbei handelt es sich (mit Schwerpunkt in den Geistes-, Sozial- und Wirtschaftswissenschaften) um die Kollektionen Arts & Sciences II, III, V, VI, VII, IX, XI und XIV mit über 1.000 ausgewählten Kernzeitschriften.
</p>

<p>
Eine Auflistung der Zeitschriftentitel der einzelnen Sammlungen können Sie über <a onclick="window.open('https://www.jstor.org', '_blank');">https://www.jstor.org/</a> einsehen. In der Regel stehen die Zeitschriften ab dem ersten Jahrgang, d. h. zum Teil sogar bis zum Anfang des 19. Jahrhunderts als elektronische Volltexte zur Verfügung. JSTOR ermöglicht die Recherche in den enthaltenen Zeitschriften und den Zugriff auf den Volltext unter einer Oberfläche. So steht eine Suchmaske zur Verfügung, die nicht nur die Suche nach Zeitschriftentiteln, sondern auch nach einzelnen Aufsätzen im gesamten Archiv ermöglicht.
</p>

<ul>
    <li><a onclick="window.open('/themes/archaeostrap/pdf/jstor.pdf', '_blank');" target="_blank">JSTOR Kurzanleitung</a></li>
    <li><a onclick="window.open('https://guides.jstor.org/researchbasics', '_blank');">Recherchehinweise auf der JSTOR-Homepage</a></li>
</ul>

<p>
Allerdings besteht bei den neuesten Jahrgängen eine sogenannte 'moving wall' von drei bis fünf Jahren, d. h., dass die aktuellen Hefte aus diesem Zeitraum über JSTOR leider nicht zugänglich sind.
</p>

<p>
JSTOR-Zeitschriften sind in die EZB integriert. Wenn Sie also in der EZB nach Zeitschriften suchen, erhalten Sie automatisch auch Treffer aus dem JSTOR-Angebot.
</p>

<p>
Alle lizenzierten eJournals sind innerhalb der Räumlichkeiten des DAI frei zugänglich. Beachten Sie bitte vor der Nutzung die <a href="#terms-of-use">Nutzungsbedingungen</a>.
</p>

<hr>

<h2>FID Altertumswissenschaften – Propylaeum</h2>

<p>
Im Kontext der aktuellen Förderung durch die DFG sorgt Propylaeum mit Hilfe sogenannter „FID-Lizenzen“ auch für die überregionale Bereitstellung lizenzpflichtiger digitaler Medien. Der Fachinformationsdienst (FID) Altertumswissenschaften bietet nach einer Registrierung für Einzelnutzerinnen und Einzelnutzer standortunabhängigen Zugang zu zahlreichen spezialisierten elektronischen Ressourcen. Auf diese Ressourcen können Sie auch außerhalb des DAI zugreifen. Über ein Online-Registrierungsverfahren können berechtigte Personen Zugangskennungen erhalten.
</p>

<p>
Weitere Informationen finden Sie unter <a onclick="window.open('https://altertum.fid-lizenzen.de', '_blank');">https://altertum.fid-lizenzen.de</a>
</p>

<p>
Die Inhalte aus den FID-Lizenzen sind nur teilweise in Zenon integriert. 
</p>

<hr>

<h2>Weitere externe Recherchemöglichkeiten</h2>

<ul>

<li>Der <a onclick="window.open('https://kvk.bibliothek.kit.edu', '_blank');">KVK</a> ist eine Buch-Suchmaschine von mehreren 100 Millionen Medien in Katalogen weltweit.</li> 
<li><a onclick="window.open('http://www.base-search.net/', '_blank');">BASE</a> (Bielefeld Academic Search Engine) ist eine Suchmaschine der Universitätsbibliothek Bielefeld für frei im Sinne des Open Access zugängliche wissenschaftliche Dokumente, deren Metadaten weltweit von Dokumentenservern bereitgestellt werden. BASE ermöglicht den Zugriff auf rund 25 Millionen Dokumente, z. B. Hochschulschriften, Preprints, Zeitschriftenartikel u. a. von 1.722 Dokumentenservern.</li>
<li><a onclick="window.open('http://www.doabooks.org/', '_blank');">DOAB</a> (Directory of Open Access Books) verzeichnet Open-Access-Bücher, deren Lizenz die freie Nachnutzung erlaubt.</li>
<li><a onclick="window.open('http://www.oclc.org/oaister.en.html', '_blank');">OAIster</a> ist ursprünglich ein Open-Access-Projekt der University of Michigan Library und mittlerweile durch OCLC übernommen, schafft Zugang zu über 23 Millionen frei verfügbaren akademischen Online-Publikationen von mehr als 1.100 Einrichtungen. Die einzelnen Datenbankeinträge sind mit aussagekräftigen Metadaten angereichert. Die Inhalte sind auch über den WorldCat verfügbar.</li>
<li><a onclick="window.open('https://www.oapen.org/home', '_blank');">OAPEN</a> Library (Open Access Publishing in European Networks) weist Open-Access-Bücher unterschiedlicher Verlage und Forschungseinrichtungen nach, die auch von Google Scholar indexiert werden.</li>

</ul>
