<div>
    <h2>iDAI.bibliography</h2>

    In iDAI.bibliography/ZENON finden Sie den Buch- und Zeitschriftenbestand der DAI-Bibliotheken inklusive Artikel aus
    Zeitschriften und Büchern, Rezensionen sowie Karten- und Archivmaterial, retrodigitalisierte Bücher und E-Books.

    <h3> Wie finde ich ein Buch oder einen Artikel in iDAI.bibliography/ZENON?</h3>
    <p>
        Sie können über das Suchfeld „Alle Felder“ beispielsweise den Verfasser und/oder Titel und/oder eindeutige
        Schlagwörter sowie Begriffe aus dem Volltext (elektronisch verfügbare Inhaltsverzeichnisse oder Medien)
        eingeben. Wenn Sie gezielt nach einem Verfasser suchen möchten, wählen Sie bitte das Suchfeld „Verfasser“ aus.
        In der „Erweiterten Suche“ werden weitere Suchoptionen angeboten sowie die Möglichkeit, einzelne Suchbegriffe
        gezielt miteinander zu verknüpfen.
    </p>
    <p>
        Über die Funktion „Suche einschränken“ können Sie Ihre Rechercheergebnisse weiter spezifizieren und somit die
        Trefferliste nachträglich weiter einschränken.
    </p>

    <h3>Wie erkenne ich, an welchem Standort ein Buch/eine Zeitschrift vorhanden ist?</h3>
    <p>
        Klicken Sie auf das Suchergebnis, dann werden Ihnen sowohl die bestandführende Bibliothek/en als auch die
        Signatur/en angezeigt.
    </p>
    <p>
        Suchen Sie gezielt nach Medien einer bestimmten Bibliothek, können Sie Ihre Suchergebnisse entsprechend filtern
        („Suche einschränken“). Klicken Sie hierzu in der rechten Menüleiste auf die entsprechende Bibliothek. Nun
        werden Ihnen als Suchergebnis nur Medien aus dem Bestand dieser Bibliothek angezeigt.
    </p>

    <h3>Ich finde keine Signatur. Was nun?</h3>
    Folgende Fälle sind möglich:
    <ul>
        <li>Es ist ein Online-Dokument. Bitte klicken Sie auf die URL.</li>
        <li>Das Werk ist noch nicht im Bestand, sondern "bestellt", "In Bearbeitung", "im Geschäftsgang", "beim Buchbinder". In diesem Fall müssen Sie sich gedulden, bis das Werk in den Bestand aufgenommen ist, d.h. bis eine Signatur angezeigt wird.</li>
    </ul>

    <h3>Wie kann ich meine Suchergebnisse speichern?</h3>
    Sie können Ihre Suche als RSS-Feed abonnieren. So werden Sie über neue Literatur, die zu Ihren Suchbegriffen im
    Katalog verzeichnet wird, informiert. Darüber hinaus können Sie Ihre Suche als E-Mail versenden oder speichern
    (diese    Funktion ist nur für angemeldete BenutzerInnen zugänglich).



    <h2>iDAI.bibliography PLUS</h2>
    <p>
        Sobald Sie sich für eine Recherche im Bestand iDAI.bibliography PLUS entschieden haben, können Sie gleichzeitig im
        Titelbestand von iDAI.bibliography <strong>UND</strong> weiteren ca. 11.000.000 bibliographischen Einträgen
        recherchieren. Darunter befinden sich beispielsweise die JSTOR-Artikel (Volltextzugriff auf dem DAI-Netz möglich),
        Artikel und Zeitschriftentitel aus den Nationallizenz-Paketen sowie lizenzfreie elektronische Ressourcen.
    </p>
    <p>Wir sind damit beschäftigt, den Bestand von iDAI.bibliography PLUS weiter aufzubereiten und auszubauen.
        Rückfragen senden Sie bitte gern an elibary@dainst.de
    </p>
</div>