<div class="row-fluid thesaurus" ng-app="zenonThs">

	<div ng-controller="ThsController" class="well span12" ng-hide="columns.length < 1 || columns[0].length < 1">
		<h4>
			<i class="icon-inbox small"></i> <?=$this->translate('Thesaurus')?>
			<i ng-show="loading > 0" class="icon-spin icon-refresh" style="margin-left: 20px;"></i>
		</h4>

		<div style="overflow-x:hidden;">

			<div ng-style="{transform: 'translate(-'+offset+'px,0)'}"
					style="transition: transform 0.5s; width:3000px;">
				<div ng-repeat="(colNo, column) in columns"
						ng-style="{width: colWidth+'px'}"
						style="height:300px; overflow:auto; display:inline-block; vertical-align:middle;">
					<ul class="nav nav-list">
						<li ng-class="{ active: active[colNo].id == entry.id }" ng-repeat="entry in column">
							<a ng-click="loadColumn(colNo+1,entry)" style="cursor:pointer;">
								<i ng-hide="entry.leaf" class="icon-chevron-right" style="float:right; margin-top:2px;"></i>
								{{ entry.heading }}
							</a>
						</li>
					</ul>
				</div>
				<div ng-show="active.length < 1"
					ng-style="{width: colWidth*3+'px'}"
					class="muted"
					style="display:inline-block; text-align:center; vertical-align:middle;">
					<i class="icon-arrow-left"></i>
					<em>Wählen Sie einen Eintrag, um eine Recherche nach einem Thesaurusbegriff zu starten.</em>
				</div>

			</div>

			<hr>

			<ul class="breadcrumb" style="margin:0; padding: 0 15px;">
			  <li><strong>Auswahl:</strong></li>
			  <li ng-show="active.length < 1" class="muted"><em>-Kein Thesaurseintrag ausgewählt-</em></li>
			  <li ng-repeat="(i,entry) in active">
			  	{{entry.heading}}
			  	<span ng-hide="i >= active.length-1" class="divider">></span>
			  </li>
			  <li class="pull-right">
			  	<a ng-class="{disabled:(active.length < 1)}" ng-click="search(active[active.length-1])" class="btn btn-primary pull-right"><i class="icon-search"></i> <?=$this->transEsc("Find")?></a>
			  </li>
			</ul>

		</div>

	</div>

	<script src="//ajax.googleapis.com/ajax/libs/angularjs/1.3.13/angular.min.js"></script>
	<script src="/themes/archaeostrap/js/thesaurus.js"></script>

</div>
