<? if ($mobileViewLink = $this->mobileUrl()): // display 'return to mobile' link when applicable ?>
  <hr/>
  <div class="mobileViewLink"><a href="<?=$this->escapeHtml($mobileViewLink)?>"><?=$this->transEsc("mobile_link")?></a></div>
<? endif; ?>
<hr/>
<div class="row-fluid small">
  <div class="span2 offset3"><p><strong><?=$this->transEsc('Search Options')?></strong></p>
    <ul>
      <li><a href="<?=$this->url('search-history')?>"><?=$this->transEsc('Search History')?></a></li>
      <li><a href="<?=$this->url('search-advanced')?>"><?=$this->transEsc('Advanced Search')?></a></li>
    </ul>
  </div>
  <div class="span2"><p><strong><?=$this->transEsc('Find More')?></strong></p>
    <ul>
      <li><a href="<?=$this->url('browse-home')?>"><?=$this->transEsc('Browse the Catalog')?></a></li>
      <!--<li><a href="<?=$this->url('alphabrowse-home')?>"><?=$this->transEsc('Browse Alphabetically')?></a></li>-->
      <!--<li><a href="<?=$this->url('search-reserves')?>"><?=$this->transEsc('Course Reserves')?></a></li>-->
      <li>
        <?
          $queryMonth = date('my');
          $queries = [];
          foreach(['a','e','i','k','c','m','o','f','r','z'] as $char) $queries[] = $char.$queryMonth;
          $query = join(' OR ', $queries);
        ?>
        <a href="<?=$this->url('search-results')?>?lookfor=<?=$query?>&amp;type=LocalNote"><?=$this->transEsc('Accessions')?></a>
      </li>
    </ul>
  </div>
  <div class="span2"><p><strong><?=$this->transEsc('Need Help?')?></strong></p>
    <ul>
      <li><a href="<?=$this->url('help-home')?>?topic=search" class="help-link" title="<?=$this->transEsc('Search Tips')?>"><?=$this->transEsc('Search Tips')?></a></li>
      <li><a href="http://www.dainst.org/forschung/infrastruktur/bibliotheken"><?=$this->transEsc('Ask a Librarian')?></a></li>
    </ul>
  </div>
</div>
<div class="row-fluid">
  <div class="span6 offset3 text-center small">
    Fragen und Hinweise zum ZENON schicken Sie bitte an <a href="mailto:zenondai@dainst.de">zenondai@dainst.de</a>.
  </div>
</div>
