<? $account = $this->auth()->getManager(); ?>
<div class="container archaeo-fixed-menu-header">
<? if (!isset($this->layout()->renderingError)): ?>
  <div class="pull-right text-right">
    <div class="btn-group control-group" style="margin-top:12px">
    <? if ($this->feedback()->tabEnabled()): ?>
      <a href="#contact_form" role="button" data-toggle="modal" class="btn btn-primary btn-mini">
        <i class="icon-envelope-alt"></i> <?=$this->transEsc("Feedback")?>
      </a>
      <span class="muted">&nbsp;/&nbsp;</span>
    <? endif; ?>
    <? $cart = $this->cart(); if ($cart->isActive()): ?>
      <a id="cartItems" class="modal-link" title="<?=$this->transEsc('View Book Bag')?>" href="<?=$this->url('cart-home')?>"><i class="icon-suitcase"></i> <strong><?=count($cart->getItems())?></strong> <?=$this->transEsc('items')?><?=$cart->isFull() ? ' (' .  $this->transEsc('bookbag_full') . ')' : ''?></a>
    <? endif; ?>
    <? if (is_object($account) && $account->loginEnabled()): // hide login/logout if unavailable ?>
      <? if($account->isLoggedIn()): ?>
        <a href="<?=$this->url('myresearch-home')?>" class="btn btn-small" title="<?=$this->transEsc("Your Account")?>"><i class="icon-home"></i> <?=$this->transEsc("Your Account")?></a>
        <a href="<?=$this->url('myresearch-logout')?>" class="btn btn-small btn-primary" title="<?=$this->transEsc("Log Out")?>"><i class="icon-signout"></i> <?=$this->transEsc("Log Out")?></a>
      <? endif; ?>
      <? if(!$account->isLoggedIn()): ?>
        <? if ($sessionInitiator = $account->getSessionInitiator($this->serverUrl($this->url('myresearch-home')))): ?>
          <a href="<?=$this->escapeHtml($sessionInitiator)?>" class="btn btn-small"><i class="icon-signin"></i> <?=$this->transEsc("Institutional Login")?></a>
        <? else: ?>
          <a href="<?=$this->url('myresearch-home')?>" class="btn btn-small btn-primary" title="<?=$this->transEsc("Login")?>"><i class="icon-signin"></i> <?=$this->transEsc("Login")?></a>
        <? endif; ?>
      <? endif; ?>
    <? endif; ?>
    </div>
    <? if (isset($this->layout()->themeOptions) && count($this->layout()->themeOptions) > 1): ?>
    <form class="form-horizontal" method="post" name="themeForm" action="" id="themeForm">
      <div class="control-group">
        <label class="control-label" for="themeForm_ui"><?=$this->transEsc("Theme")?>:</label>
        <div class="controls">
          <select onChange="document.themeForm.submit()" id="themeForm_ui" name="ui">
          <? foreach ($this->layout()->themeOptions as $current): ?>
            <option value="<?=$this->escapeHtml($current['name'])?>"<?=$current['selected'] ? ' selected="selected"' : ''?>><?=$this->transEsc($current['desc'])?></option>
          <? endforeach; ?>
          </select>
          <noscript><input type="submit" value="<?=$this->transEsc("Set")?>" /></noscript>
        </div>
      </div>
    </form>
    <? endif; ?>
    <? if ($this->feedback()->tabEnabled()): ?>
      <?=$this->render('feedback/form.phtml'); ?>
    <? endif; ?>
    <? if (isset($this->layout()->allLangs) && count($this->layout()->allLangs) > 1): ?>
    <form class="form-horizontal" method="post" name="langForm" action="" id="langForm">
      <label class="control-label small" for="langForm_mylang"><?=$this->transEsc("Language")?>:</label>
      <div class="controls">
        <select onChange="document.langForm.submit()" id="langForm_mylang" name="mylang" class="form-control input-small small">
        <? foreach ($this->layout()->allLangs as $langCode => $langName): ?>
          <option value="<?=$langCode?>"<?=$this->layout()->userLang == $langCode ? ' selected="selected"' : ''?>><?=$this->displayLanguageOption($langName)?></option>
        <? endforeach; ?>
        </select>
        <noscript><input type="submit" class="btn" value="<?=$this->transEsc("Set")?>" /></noscript>
      </div>
    </form>
    <? endif; ?>
  </div>
<? endif; ?>
        <a href="http://www.dainst.org">
                <div id="archaeo-fixed-menu-logo"></div>
        </a>
        <a href="<?=$this->url('home')?>">
                <h3 class="pull-left">
                        <small>Deutsches Archäologisches Institut</small>
                        <br>
                        <span style="color:#2E2E2E">ZENON <small><b>beta</b></small></span>
                </h3>
        </a>
</div>
