<? $account = $this->auth()->getManager(); ?>
<div class="navbar-header">
  <div style="padding-left:0px; position:relative">
      <div class="pull-left">
          <ul class="nav navbar-nav">
              <li class="dropdown" dropdown>
                  <a href="#" dropdown-toggle class="dropdown-toggle" data-toggle="dropdown">
                      <img src="<?=$this->imageLink('kleinergreif.png') ?>"
                          style="height: 38px; margin-top: -16px; margin-bottom: -14px">
                      <b class="caret"></b>
                  </a>
                  <ul class="dropdown-menu" dropdown-menu>
                      <li><a href="http://www.dainst.org/de/forschung/forschung-digital/idai.welt" target="_blank">iDAI.welt</a></li>
                      <li class="divider"></li>
                      <li><a href="https://gazetteer.dainst.org/" target="_blank">iDAI.gazetteer</a></li>
                      <li><a href="http://geoserver.dainst.org/" target="_blank">iDAI.geoserver</a></li>
                      <li><a href="http://arachne.uni-koeln.de/" target="_blank">iDAI.objects&nbsp;/&nbsp;Arachne</a></li>
                      <li><a href="http://zenon.dainst.org" target="_blank">iDAI.bibliography&nbsp;/&nbsp;Zenon</a></li>
                      <li><a href="http://archwort.dainst.org/thesaurus/de/vocab" target="_blank">iDAI.vocab</a></li>
                      <li><a href="http://hellespont.dainst.org" target="_blank">Hellespont</a></li>
                  </ul>
              </li>
          </ul>
      </div>
      <a href="/">
          <img class="pull-left" src="<?=$this->imageLink('logo_zenon.png') ?>" style="height: 36px; margin-top: 8px;">
      </a>
  </div>
</div>
<? if ($this->layout()->searchbox !== false): ?>
  <section class="visible-lg">
    <?=$this->layout()->searchbox ?>
  </section>
<? endif; ?>
<? if (!isset($this->layout()->renderingError)): ?>
  <div class="collapse navbar-collapse" id="header-collapse" style="padding-right: 15px;">
    <nav>
      <ul class="nav navbar-nav navbar-right flip">
        <? if ($this->layout()->searchbox == false): ?>
          <li>
            <a href="<?=$this->url("search-advanced")?>"><?=$this->transEsc("Advanced Search")?></a>
          </li>
        <? endif; ?>
        <? if ($this->feedback()->tabEnabled()): ?>
          <li>
            <a id="feedbackLink" class="modal-link" href="<?=$this->url('feedback-home') ?>"><i class="fa fa-envelope"></i> <?=$this->transEsc("Feedback")?></a>
          </li>
        <? endif; ?>
        <? $cart = $this->cart(); if ($cart->isActive()): ?>
          <li id="cartSummary">
            <a id="cartItems" class="modal-link" title="<?=$this->transEsc('View Book Bag')?>" href="<?=$this->url('cart-home')?>"><i class="fa fa-suitcase"></i> <strong><?=count($cart->getItems())?></strong> <?=$this->transEsc('items')?><?=$cart->isFull() ? ' (' .  $this->transEsc('bookbag_full') . ')' : ''?></a>
          </li>
        <? endif; ?>
        <? if (is_object($account) && $account->loginEnabled()): // hide login/logout if unavailable ?>
          <li class="logoutOptions<? if(!$account->isLoggedIn()): ?> hidden<? endif ?>">
            <a href="<?=$this->url('myresearch-home', array(), array('query' => array('redirect' => 0)))?>" class="modal-link" title="<?=$this->transEsc("Your Account")?>"><i class="fa fa-home"></i> <?=$this->transEsc("Your Account")?></a>
          </li>
          <li class="logoutOptions<? if(!$account->isLoggedIn()): ?> hidden<? endif ?>">
            <a href="<?=$this->url('myresearch-logout')?>" class="modal-link" title="<?=$this->transEsc("Log Out")?>"><i class="fa fa-sign-out"></i> <?=$this->transEsc("Log Out")?></a>
          </li>
          <li id="loginOptions"<? if($account->isLoggedIn()): ?> class="hidden"<? endif ?>>
            <? if ($sessionInitiator = $account->getSessionInitiator($this->serverUrl($this->url('myresearch-home')))): ?>
              <a href="<?=$this->escapeHtmlAttr($sessionInitiator)?>"><i class="fa fa-sign-in"></i> <?=$this->transEsc("Institutional Login")?></a>
            <? else: ?>
              <a href="<?=$this->url('myresearch-userlogin')?>" class="modal-link" title="<?=$this->transEsc("Login")?>"><i class="fa fa-sign-in"></i> <?=$this->transEsc("Login")?></a>
            <? endif; ?>
          </li>
        <? endif; ?>

        <? if (isset($this->layout()->themeOptions) && count($this->layout()->themeOptions) > 1): ?>
          <li class="dropdown">
            <form method="post" name="themeForm" id="themeForm">
              <input type="hidden" name="ui"/>
            </form>
            <a href="#" class="dropdown-toggle" data-toggle="dropdown"><?=$this->transEsc("Theme")?> <b class="caret"></b></a>
            <ul class="dropdown-menu">
              <? foreach ($this->layout()->themeOptions as $current): ?>
                <li<?=$current['selected'] ? ' class="active"' : ''?>><a href="#" onClick="document.themeForm.ui.value='<?=$this->escapeHtmlAttr($current['name'])?>';document.themeForm.submit()"><?=$this->transEsc($current['desc'])?></a></li>
              <? endforeach; ?>
            </ul>
          </li>
        <? endif; ?>

        <? if (isset($this->layout()->allLangs) && count($this->layout()->allLangs) > 1): ?>
          <li class="dropdown">
            <form method="post" name="langForm" id="langForm">
              <input type="hidden" name="mylang"/>
            </form>
            <a href="#" class="dropdown-toggle" data-toggle="dropdown"><?=$this->transEsc("Language")?> <b class="caret"></b></a>
            <ul class="dropdown-menu">
              <? foreach ($this->layout()->allLangs as $langCode => $langName): ?>
                <li<?=$this->layout()->userLang == $langCode ? ' class="active"' : ''?>><a href="#" onClick="document.langForm.mylang.value='<?=$langCode?>';document.langForm.submit()"><?=$this->displayLanguageOption($langName)?></a></li>
              <? endforeach; ?>
            </ul>
          </li>
        <? endif; ?>
      </ul>
    </nav>
  </div>
<? endif; ?>
